import ControlExercicios

if __name__ == '__main__':
    ControlExercicios.exerciciocontrol1()
    "\n"
    ControlExercicios.exerciciocontrol2()
    "\n"
    ControlExercicios.exerciciocontrol3()
    "\n"
    ControlExercicios.exerciciocontrol4()
    "\n"
    ControlExercicios.exerciciocontrol5()
    "\n"
    ControlExercicios.exerciciocontrol6()
    "\n"
    ControlExercicios.exerciciocontrol7()
    "\n"
    ControlExercicios.exerciciocontrol8()
    "\n"
    ControlExercicios.exerciciocontrol9()
    "\n"
    """ControlExercicios.exerciciocontrol10()"""
    ControlExercicios.exerciciocontrol11()
    "\n"
    ControlExercicios.exerciciocontrol12()
    "\n"
    ControlExercicios.exerciciocontrol13()
    "\n"
    ControlExercicios.exerciciocontrol14()
    "\n"
    ControlExercicios.exerciciocontrol15()
    "\n"
    ControlExercicios.exerciciocontrol16()
    "\n"
    ControlExercicios.exerciciocontrol17()
    "\n"
    ControlExercicios.exerciciocontrol18()
    "\n"
    ControlExercicios.exerciciocontrol19()